### ISSUE TITLE
Nuget Package Error

### ISSUE THREAD

**Issue by KenticoDevTrev** [CMeeg/kentico-contrib#2]
Getting this error when trying to install Meeg.Kentico.ContentComponents on my MVC Site:

Error		Could not install package 'Meeg.Kentico.ContentComponents.Cms 0.1.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.					

If you can republish awesome, i'm actually needing this for a demonstration at a talk I'm giving on Data Modeling and would love to give a plug in for it :)

**Comment by KenticoDevTrev** [comment]
Adding a new note to this, it looks like this was built in 4.7.2, which Kentico 12 is available in 4.6.1 upwards, so this module cannot be installed on any Kentico instance that is using the base .net framework.

Is there anyway you could repackage this in 4.6.1, since that can be used on any K12 instance 4.6.1 upwards?

**Comment by CMeeg** [comment]
Hi @KenticoDevTrev thanks for getting in touch. The first thing I do on a new Kentico project is update the target framework and I hadn't considered the impact of that in relation to these packages. Targeting the lowest possible framework version makes sense. I can't think of anything in these particular packages that requires 4.7.2 so dropping back to 4.6.1 shouldn't be an issue.

As soon as I get the time I will look at doing so. No promises, but when is your demo?

**Comment by KenticoDevTrev** [comment]
It's Saturday but no big rush, I forked it, changed the frameworks and integrated it manually and got it working without the nuget package, pretty slick! Looking forward to when it's installable in the nuget package!

**Comment by KenticoDevTrev** [comment]
Also Matt is wondering why you didn't tell him about this ;)

**Comment by KenticoDevTrev** [comment]
Any luck on the rebuild in 4.6.1?  I'm going to do a manual install of it again, if you can get it rebuilt on 4.6.1 that would really rock!

**Comment by CMeeg** [comment]
Hi @KenticoDevTrev, it's taken me a while to get to this, but I will push a new release some time this weekend that will include this and a fix for #3.
